- name: install pip
  yum:
    name: python3-pip
    state: present

- name: install Docker dependencies with pip
  pip:
    name:
      - docker
      - docker-compose

- name: run container
  docker_container:
    name: wartest
    image: "{{ image }}"
    ports:
      - "8081:8080"
    state: started
